### ISSUE TITLE
Container::getComponent() throws exception for already attached components

### ISSUE THREAD

**Issue by iinfo-dev-mk** [nette/component-model#1]
Because there is a check for component parent presence in https://github.com/nette/component-model/blob/master/src/ComponentModel/Container.php#L142 it's impossible return already created and attached controls.

``` php
class MyControl {

protected function createComponentTest() {
  return $this->anotherControlParent->getComponent("Test");
}
```

If another parent has attached component "test", exception about unknown component "test" is thrown. Throw such exception in this situation is misleading.

Maybe such component don't need to be attached to _current_ parent but getComponent() method can return such component. That component is already attached to another parent doesn't matter.

**Comment by dg** [comment]
Component with a parent are linked together, it is not possible to have component with two parents.

**Comment by iinfo-dev-mk** [comment]
Yes, I know, I don't want to have component with 2 parents. I have component linked with some parent (e.g. "anotherClass", it's special class Presenter in my case) and I want to access it (maybe through another name) in some component through CurrentComponent::getComponent("other"), so I created

``` php
class CurrentComponent {
  protected function createComponentOther() {
    return $this->lookup("anotherClass")->getComponent("another");
 }
}
```

and exception is thrown. And there is no reason for that. CurrentComponent::getComponent("other") can return such component without any problem, only it won't bind it to the CurrentComponent tree.

I think it worked as I expected in some older nette (2.0 maybe)

**Comment by fprochazka** [comment]
@iinfo-dev-mk you're using it wrong. You've created component factory, that fetches another component that already has a parent. And component factories are used for binding components to the component tree. Therefore it tries to set the parent, which is not possible, because the component already has a parent.

Create a simple getter, instead of a component factory. This has never worked.

**Comment by iinfo-dev-mk** [comment]
@fprochazka I think it worked, because current code was in createComponent() call and such component was simple returned - as I wrote - but it doesn't matter.
Can you explain getter solution? Which getter? I want use same access style for such component - $this["other"] => getComponent("other")
So what getter I need? Or override getComponent() in CurrentComponent and for "other" parameter return $this->lookup("anotherClass")->getComponent("another")?

**Comment by iinfo-dev-mk** [comment]
But throw exception  Nette\InvalidArgumentException("Component with name 'other' does not exist.") in such cases is misleading anyway.
Exception "Component for name 'other' is already linked with some parent" is much more appropriate.

**Comment by dg** [comment]
Fixed exception message.

**Comment by iinfo-dev-mk** [comment]
Thank for fix exception message, can it be backported to 2.2 branch please?

@dg, @fprochazka Can you explain me please, how can I achieve my goal - access some component with already connected parent through $this["other"] => getComponent("other") in some other component?

**Comment by JanTvrdik** [comment]
@iinfo-dev-mk Easy, use a different framework. What you want should never ever work in Nette.

**Comment by PavelJurasek** [comment]
@iinfo-dev-mk Don't you want to just access subcomponent? `$this['component']['subcomponent']`?

**Comment by iinfo-dev-mk** [comment]
@JanTvrdik Hm, odd, singleton behavior for component is very useful pattern, it can save a lot of resources. I will try to override the getComponent method as @fprochazka dropped a hint.
@PavelJurasek no, this is completely different case.

So I finish the debate, there is no chance to change getComponent behavior in nette, I eventually open some topic in forum.

**Comment by dg** [comment]
Component model in Nette is similar to DOM. It is not possible to have the same element on two or more places. 

You can access component with already connected parent through $firstObject["other"], but you can't connect it to $secondObject, unless you disconnect it from $firstObject. Because each component has only single property $parent.

**Comment by fprochazka** [comment]
@iinfo-dev-mk I've told you to create getter, not overwrite the behaviour.

**Comment by iinfo-dev-mk** [comment]
@fprochazka this is useless for my goal
@dg I understand and I don't want to break this one, but _outside_ representation through getComponent() and especially {control 'name' } macro can return whatever component user want, not only correctly connected components - it _internally_ in sense of component trees breaks nothing, just helps to realize some useful patterns like singleton behavior component.

**Comment by iinfo-dev-mk** [comment]
As I mentioned, thank you all for your opinions, it's design decision, I'll eventually discuss this one in the forum.

**Comment by dg** [comment]
getComponent is public method, you can easily overwrite it.

**Comment by iinfo-dev-mk** [comment]
Yes, it's what I mentioned in [earlier](https://github.com/nette/component-model/issues/1#issuecomment-72680779), I'll try
