### ISSUE TITLE
attached() is called more than once with the same monitored class

### ISSUE THREAD

**Issue by VladaHejda** [nette/component-model#2]
When component monitors e.g. interface and monitors its descendant too, the `attached()` method is called twice with the same monitored object.

Following sandbox branch calls `attached()` with Presenter twice:

[VladaHejda:double-monitoring](https://github.com/nette/sandbox/compare/v2.3.2...VladaHejda:double-monitoring)

**Comment by dg** [comment]
It seems ok to me.
