### ISSUE TITLE
Can Container implement IteratorAgregate?

### ISSUE THREAD

**Issue by h4kuna** [nette/component-model#7]
Describe use case:
If i prepare structure of the form by `$form->addContainer('foo');` in every template i must use `{foreach $form->getComponent('foo')->getComponents() as $key => $input}` this help make shorter `{foreach $form->getComponent('foo') as $key => $input}`, because i never need parameters from getComponents() $deep and $fileter in template.

Implementation is easy.
```php
namespace Nette\ComponentModel;

use Nette;

class Container extends Component implements IContainer, \IteratorAggregate
{

	public function getIterator()
	{
		return $this->getComponents();
	}

}
```

What do you think?

**Comment by dg** [comment]
It's a huge BC break with minimal added value.
